# Project
version=1.2.1+26.1.2
group=com.illusivesoulworks.polymorph
java_version=25

# Common
minecraft_version=26.1.2
mod_name=Polymorph
mod_author=Illusive Soulworks
mod_id=polymorph
license=LGPL-3.0-or-later
issues_url=https://github.com/nnmrts/polymorph/issues
sources_url=https://github.com/nnmrts/polymorph
description=No more recipe conflicts! Adds an option to choose the crafting result if more than one is available.
minecraft_version_range=[26.1.0, 26.2)
minecraft_version_range_alt=~26.1.0

# Parchment
#parchment_mc=1.21.10
#parchment_version=2025.10.12

# Integrations
#emi_version=1.1.22+1.21.1
jei_version=29.5.0.28
#rei_version=21.9.812

# Fabric
fabric_version=0.148.0+26.1.2
fabric_loader_version=0.19.2
cca_version=8.0.0

# Modrinth
modrinth_id=KTZoLgc9
modrinth_page=https://modrinth.com/project/polymorph-but-its-for-fabric-only-but-also-for-1.21.10
release_type=release
release_versions=1.21.10
changelog_link=https://github.com/nnmrts/polymorph/blob/1.21.10/CHANGELOG.md

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
